
# from galaxy
- src: geerlingguy.security
  version: 1.5.0

- src: zzet.rbenv
  version: 3.0.0

- src: jdauphant.nginx
  version: v2.7.4

- src: thefinn93.letsencrypt
  # version:

- src: conorsch.create-droplet
